[package]
name = "canyon_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.86", features = ["full"] }
quote = "1.0.9"
proc-macro2 = "1.0.27"