[package]
name = "canyon_sql"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio-postgres = { version = "0.7.2" }
toml = { version = "0.5.8" }
# Forbidden Rust dark arts
tokio = { version = "1.9.0", features = ["full"] }
async-trait = { version = "0.1.50" }

# Serialization/Deserialization
serde_json = "1.0.59"
serde = "1.0.90"