# This is the root Caasdfadsrgo.tomlsda file that serves as manager for the workspace of the project
[package]
name = "canyon_sql"
version = "0.2.0"

[workspace]
members = [
    "canyon_observer",
    "canyon_macros",
    "canyon_crud",
    "canyon_connection",

    "tests"
]

[workspace.dependencies]
# Project crates
canyon_macros = { version = "0.2.0", path = "canyon_macros" }
canyon_observer = { version = "0.2.0", path = "canyon_observer" }
canyon_crud = { version = "0.2.0", path = "canyon_crud", features = ["postgres", "mssql"]  }
canyon_connection = { version = "0.2.0", path = "canyon_connection", features = ["postgres", "mssql"] }

tokio = { version = "1.21.2", features = ["full"]  }
tokio-util = { version = "0.7.4", features = ["compat"]  }
tokio-postgres = { version = "0.7.2", features = ["with-chrono-0_4"] }
tiberius = { version = "0.12.1", features = ["tds73", "chrono", "integrated-auth-gssapi"] }

futures = "0.3.25"
indexmap = "1.9.1"
async-std = "1.12.0"
lazy_static = "1.4.0"
serde = { version = "1.0.138", features = ["derive"] }
toml = "0.7.3"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Alex Vergara<pyzyryab@tutanota.com>, Gonzalo Busto<gbm25@gmail.com>"]
documentation = "https://zerodaycode.github.io/canyon-book/"
homepage = "https://github.com/zerodaycode/Canyon-SQL"
readme = "../README.md"
license = "MIT"
description = "A Rust ORM and QueryBuilder"
