[package]
name = "canyon_connection"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.9.0", features = ["full"] }
tokio-postgres = { version = "0.7.2", features=["with-chrono-0_4"] }
lazy_static = "1.4.0"