[package]
name = "canyon_connection"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.9.0", features = ["full"] }
tokio-postgres = { version = "0.7.2", features = ["with-chrono-0_4"] }

tiberius = { version = "0.10.0", features = ["tds73", "chrono"] }
async-std = { version = "1.12.0" }

lazy_static = "1.4.0"

serde = { version = "1.0.138", features = ["derive"] }
toml = "0.5.9"