services:
  postgres:
    image: postgres:14
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/10-create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/20-fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1434:1433"
    environment:
      MSSQL_SA_PASSWORD: "SqlServer-10"
      ACCEPT_EULA: "Y"
  mysql:
      image: mysql:latest
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - '3307:3306'
      volumes:
        - ./mysql-data:/var/lib/mysql
        - ./mysql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        - ./mysql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql