[package]
name = "canyon_crud"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
async-trait = { version = "0.1.50" }

canyon_connection = { path = "../canyon_connection" }