[package]
name = "canyon_crud"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.9.0", features = ["full"] }
async-trait = { version = "0.1.50" }

canyon_connection = { path = "../canyon_connection" }