[package]
name = "canyon_macros"
version = "1.0.0"
edition = "2021"

[dependencies]
syn = { version = "1.0.86", features = ["full"] }
quote = "1.0.9"
proc-macro2 = "1.0.27"
futures = "0.3.21"
tokio = { version = "1.9.0", features = ["full"] }


canyon_observer = { path = "../canyon_observer" }
canyon_manager = { path = "../canyon_manager" }
canyon_crud = { path = "../canyon_crud" }
canyon_connection = { path = "../canyon_connection" }

[lib]
proc-macro = true
