[package]
name = "canyon_macros"
version = "0.1.0"
edition = "2018"

[dependencies]
syn = { version = "1.0.86", features = ["full"] }
quote = "1.0.9"
proc-macro2 = "1.0.27"
futures = "0.3.21"
canyon_observer = { path = "../canyon_observer" }

[lib]
proc-macro = true
