name: Run the tests for the project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests-unix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests Unix
      working-directory: ./canyon_sql
      run: cargo test --verbose
    
  tests-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests for Windows
      working-directory: ./canyon_sql
      run: cargo test --verbose

  tests-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests for macOS
      working-directory: ./canyon_sql
      run: cargo test --verbose
