name: Run the tests for the project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # tests-unix:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Run tests Unix
  #     working-directory: ./canyon_sql
  #     run: cargo test --verbose
    
  # tests-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Run tests for Windows
  #     working-directory: ./canyon_sql
  #     run: cargo test --verbose

  # tests-macos:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v3
    # - name: Run tests for macOS
    #   working-directory: ./canyon_sql
    #   run: cargo test --verbose

  gcov:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./canyon_sql
      steps:
        - uses: actions/checkout@v3
        - name: Use nightly toolchain
          working-directory: ./canyon_sql
          run: |
            rustup toolchain install nightly
            rustup override set nightly
        - name: Run tests
          working-directory: ./canyon_sql
          run: cargo test --all-features --no-fail-fast
          env:
            CARGO_INCREMENTAL: '0'
            RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
            RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
        - uses: actions-rs/grcov@v0.1
          with:
            config: .github/workflows/tests.yml
            output-type: xml
            output-path: ./test_results
        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action@v2
          if: always()
          with:
            junit_files: "test-results/**/*.xml"